完成
chenchunyii/taipei-day-trip pull request #4
Opened 2022-12-01 19:13 UTC by jokersaysjoke

http://13.112.252.173:3000/

我是群嶧 ~

2022-12-01 20:07 UTC, jokersaysjoke commented
http://13.112.252.173:3000/

我是群嶧 ~

2022-12-02 04:17 UTC, cwpeng requested changes
Layout issue: color, width of separator lines.

2022-12-02 05:53 UTC, jokersaysjoke commented
http://13.112.252.173:3000/
修改分隔邊框顏色

我是群嶧~

2022-12-02 06:18 UTC, jokersaysjoke commented
http://13.112.252.173:3000/
修改分隔邊框顏色

我是群嶧~

2022-12-02 06:55 UTC, cwpeng approved these changes
OK. Done.

2022-12-02 08:38 UTC, merged